#!/usr/bin/python3

import re
from urllib.request import urlopen
from bs4 import BeautifulSoup as bs

url = 'https://www.naver.com'
html = urlopen(url).read()

bsObj = bs(html, 'html.parser')
list = bsObj.find_all('span')

p = re.compile('class="ah_k">(.*)</span>')

num = 1
for item in list:
	Obj = p.search(str(item))
	if(Obj):
		print(num,":",Obj.group(1))
		num +=1
		if num>20 : 
			break;


